export var errCode={
	401:"This channel is not valid",
	402:"Invalid Mobile No. Please Try again",
	403:"Invalid email Id. Please try again",
	404:"Access denied. You are not authorized",
	405:"Your email is not verified. Please verify",
	406:"Your mobile no. is not verified. Please verify",
	407:"Your email is not registered. Please register",
	408:"Your mobile no. is not registered. Please register",
	411:"Token not generated",
	412:"Sms sending failed",
	413:"Request not valid",
	414:"Wrong OTP. Please enter correct OTP",
	415:"Your OTP has expired. Try again",
	417:"Invalid Password",
	419:"Wrong Password",
	420:"Please enter a valid Name",
	421:"Please enter a valid Gender",
	422:"Email entered is already registered",
	423:"Mobile no. entered is already registered",
	424:"Invalid OTP. Please enter correct OTP",
	425:"Wrong OTP. Please enter correct OTP",
	427:"Email is not valid",
	428:"Email is not valid",
	429:"This id is already registered with us",
	430:"Invalid Password. Please Try again",
	431:"Invalid Date of Birth. Please enter correct Date of Birth",
	432:"This mobile no. is blocked",
	434:"Error",
	435:"Can't add email. Max limit reached",
	436:"First name can't be empty. Please add",
	439:"Invalid access",
	441:"External API error",
	442:"Image upload Failed. Try again",
	444:"Error importing image. Try again",
	445:"Image not found",
	446:"your country code is not valid",
	447:"Your city is not valid",
	451:"Invalid Captcha",
	452:"Invalid Package",
	453:"Invalid Hashkey",
	455:"The user id entered is blocked",
	456:"The user id entered has opted out",
	457:"Token expired",
	458:"Channel token is invalid",
	459:"Subscription token is invalid",
	467:"Your IP gas been blocked",
	468:"Unauthenticated user",
	469:"Something went wrong",
	409:"Something went wrong",
	410:"Something went wrong",
	416:"Something went wrong",
	418:"Something went wrong",
	426:"Something went wrong",
	433:"This email /mobile no is already verfied",
	437:"Something went wrong",
	438:"Something went wrong",
	440:"Something went wrong",
	443:"Something went wrong",
	448:"Something went wrong",
	449:"Something went wrong",
	450:"Something went wrong",
	454:"Something went wrong",
	460:"Something went wrong",
	461:"Something went wrong",
	462:"Something went wrong",
	463:"Something went wrong",
	464:"Something went wrong",
	465:"Something went wrong",
	466:"Something went wrong"
}